#!/bin/bash

#PBS -N L1EM_NB_240626_175Samples
#PBS -P xw67
#PBS -q normalbw
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=48:00:00
#PBS -M ndeshpande@ccia.org.au
#PBS -m ae
#PBS -j oe
#PBS -l storage=gdata/ew19+gdata/ug9+gdata/if89+scratch/xw67+scratch/ew19

# Load nextflow module
module load java/jdk-17.0.2 nextflow/24.04.1

cd $PBS_O_WORKDIR

mkdir -p cache_dirs/{singularity_cache,nextflow_singularity_cache,singularity_temp}

export CACHE_BASE=$(pwd)/cache_dirs
export SINGULARITY_CACHEDIR="$CACHE_BASE/singularity_cache"
export NXF_SINGULARITY_CACHEDIR="$CACHE_BASE/nextflow_singularity_cache"
export SINGULARITY_TMPDIR="$CACHE_BASE/singularity_temp"

export SINGULARITY_MOUNT_TIMEOUT=900
export NXF_JAVA_OPTIONS="-Xmx120G"  # Adjust as needed



# Samplesheet

#SAMPLES_FILE="samplesheet.csv"
#SAMPLES_FILE="samplesheet_subset.csv"
#SAMPLES_FILE="samplesheet_test.csv"
#SAMPLES_FILE="samplesheet_200526_text.csv"
#SAMPLES_FILE="samplesheet_050626_testMultipleSamples.csv"
#SAMPLES_FILE="samplesheet_debug_SarahsList.csv"

# Remember NOT ALL NB processed samples had Transcriptome bams (?) - Or multi-sample per patient etc ...need to check
SAMPLES_FILE="/scratch/ew19/nandan/nextflow/2026/L1EM/download_bams/NB/samplesheet_NB_240626_combined_175Samples.csv"


# Run TN L1 only
#nextflow run main.nf -resume --samples "$SAMPLES_FILE"
nextflow run main.nf --samples "$SAMPLES_FILE"

